version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-user
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: movies
    ports:
      - '27017-27019:27017-27019'
    networks:
      app-env:
  mongoexpress:
    image: mongo-express
    container_name: 'mongo-express'
    ports:
        - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_ADMINUSERNAME: root-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      app-env:
  frontend:
    build: ./../ui
    container_name: frontend
    ports:
       - "80:80"
    networks:
      app-env:

networks:
  app-env: