version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-user
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: movies
    networks:
      app-env:
  mongoexpress:
    image: mongo-express
    container_name: 'mongo-express'
    ports:
        - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_ADMINUSERNAME: root-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      app-env:
  backend:
    build: ./../server
    container_name: backend
    ports:
        - "8080:8080"
    environment:
      MONGODB_USERNAME: root-user
      MONGODB_PASSWORD: secret
      MONGODB_ENDPOINT: mongo:27017
    depends_on: 
      - mongodb
    networks:
      app-env:

networks:
  app-env: